version: 2

updates:
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      web-dependencies:
        patterns:
          - '*'
    reviewers:
      - Rentars/maintainers
    labels:
      - dependencies
      - frontend

  - package-ecosystem: npm
    directory: /apps/backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      backend-dependencies:
        patterns:
          - '*'
    reviewers:
      - Rentars/maintainers
    labels:
      - dependencies
      - backend

  - package-ecosystem: cargo
    directory: /apps/contracts
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    reviewers:
      - Rentars/maintainers
    labels:
      - dependencies
      - contracts

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    reviewers:
      - Rentars/maintainers
    labels:
      - dependencies
      - ci
